from rule_engine import DecisionDiagnosticRule, flag, review_flag, rule_present


ELIGIBILITY_HOUSEHOLD_RULES: list[DecisionDiagnosticRule] = [
    {
        "severity": "Warning",
        "category": "Household",
        "message": None,
        "message_from_rule_id": "spouse_requires_year_end_status",
        "when": lambda context, decision, rule_result_by_id: review_flag(decision, "spouse_requires_year_end_status"),
    },
    {
        "severity": "High",
        "category": "Household",
        "message": None,
        "message_from_rule_id": "spouse_support_restriction",
        "when": lambda context, decision, rule_result_by_id: rule_present(rule_result_by_id, "spouse_support_restriction"),
    },
    {
        "severity": "Info",
        "category": "Household",
        "message": "Spouse amount settings have been reviewed. If the final spouse-related amount still looks off, check spouse net income and any support or separation details.",
        "message_from_rule_id": None,
        "when": lambda context, decision, rule_result_by_id: rule_present(rule_result_by_id, "spouse_household_path_reviewed")
        and not flag(context, "separated_in_year"),
    },
    {
        "severity": "High",
        "category": "Household",
        "message": None,
        "message_from_rule_id": "eligible_dependant_support_review",
        "when": lambda context, decision, rule_result_by_id: review_flag(decision, "eligible_dependant_support_review"),
    },
    {
        "severity": "High",
        "category": "Household",
        "message": None,
        "message_from_rule_id": "eligible_dependant_other_claimant",
        "when": lambda context, decision, rule_result_by_id: rule_present(rule_result_by_id, "eligible_dependant_other_claimant"),
    },
    {
        "severity": "High",
        "category": "Household",
        "message": None,
        "message_from_rule_id": "caregiver_other_claimant",
        "when": lambda context, decision, rule_result_by_id: rule_present(rule_result_by_id, "caregiver_other_claimant"),
    },
    {
        "severity": "Warning",
        "category": "Household",
        "message": None,
        "message_from_rule_id": "caregiver_target_ambiguous",
        "when": lambda context, decision, rule_result_by_id: review_flag(decision, "caregiver_target_ambiguous"),
    },
    {
        "severity": "Warning",
        "category": "Household",
        "message": None,
        "message_from_rule_id": "caregiver_dependant_category_review",
        "when": lambda context, decision, rule_result_by_id: review_flag(decision, "caregiver_dependant_category_review"),
    },
    {
        "severity": "Info",
        "category": "Household",
        "message": None,
        "message_from_rule_id": "caregiver_supporting_context_missing",
        "when": lambda context, decision, rule_result_by_id: review_flag(decision, "caregiver_supporting_context_missing"),
    },
    {
        "severity": "High",
        "category": "Household",
        "message": None,
        "message_from_rule_id": "disability_transfer_other_claimant",
        "when": lambda context, decision, rule_result_by_id: rule_present(rule_result_by_id, "disability_transfer_other_claimant"),
    },
    {
        "severity": "Warning",
        "category": "Household",
        "message": None,
        "message_from_rule_id": "disability_transfer_source_ambiguous",
        "when": lambda context, decision, rule_result_by_id: review_flag(decision, "disability_transfer_source_ambiguous"),
    },
    {
        "severity": "Warning",
        "category": "Household",
        "message": None,
        "message_from_rule_id": "spouse_disability_transfer_unavailable",
        "when": lambda context, decision, rule_result_by_id: review_flag(decision, "spouse_disability_transfer_unavailable"),
    },
    {
        "severity": "Warning",
        "category": "Household",
        "message": None,
        "message_from_rule_id": "dependant_disability_transfer_unavailable",
        "when": lambda context, decision, rule_result_by_id: review_flag(decision, "dependant_disability_transfer_unavailable"),
    },
    {
        "severity": "Warning",
        "category": "Household",
        "message": None,
        "message_from_rule_id": "spouse_disability_transfer_exceeds_available",
        "when": lambda context, decision, rule_result_by_id: review_flag(decision, "spouse_disability_transfer_exceeds_available"),
    },
    {
        "severity": "Warning",
        "category": "Household",
        "message": None,
        "message_from_rule_id": "dependant_disability_transfer_exceeds_available",
        "when": lambda context, decision, rule_result_by_id: review_flag(decision, "dependant_disability_transfer_exceeds_available"),
    },
    {
        "severity": "Info",
        "category": "Household",
        "message": None,
        "message_from_rule_id": "disability_transfer_no_source_context",
        "when": lambda context, decision, rule_result_by_id: review_flag(decision, "disability_transfer_no_source_context"),
    },
    {
        "severity": "Warning",
        "category": "Household",
        "message": None,
        "message_from_rule_id": "medical_dependants_shared_review",
        "when": lambda context, decision, rule_result_by_id: review_flag(decision, "medical_dependants_shared_review"),
    },
    {
        "severity": "Info",
        "category": "Household",
        "message": None,
        "message_from_rule_id": "medical_dependants_minor_child_review",
        "when": lambda context, decision, rule_result_by_id: review_flag(decision, "medical_dependants_minor_child_review"),
    },
]
