from .rules_household import ELIGIBILITY_HOUSEHOLD_RULES
from .rules_refundables import (
    ELIGIBILITY_POSTCALC_PAYROLL_RULES,
    ELIGIBILITY_POSTCALC_REFUNDABLE_RULES,
    ELIGIBILITY_REFUNDABLE_RULES,
)


ELIGIBILITY_DIAGNOSTIC_RULES = (
    ELIGIBILITY_HOUSEHOLD_RULES
    + ELIGIBILITY_REFUNDABLE_RULES
)

ELIGIBILITY_POSTCALC_RULES = (
    ELIGIBILITY_POSTCALC_REFUNDABLE_RULES
    + ELIGIBILITY_POSTCALC_PAYROLL_RULES
)
