from .rules_carryforwards import CARRYFORWARD_RULES, POSTCALC_CARRYFORWARD_RULES
from .rules_foreign import FOREIGN_RULES
from .rules_household import HOUSEHOLD_RULES
from .rules_income import INCOME_INPUT_RULES, WITHHOLDING_RULES
from .rules_provincial import POSTCALC_PROVINCIAL_RULES, PROVINCIAL_RULES
from .rules_refundables import POSTCALC_REFUNDABLE_RULES, REFUNDABLE_RULES


CONTEXT_DIAGNOSTIC_RULES = (
    INCOME_INPUT_RULES
    + HOUSEHOLD_RULES
    + CARRYFORWARD_RULES
    + FOREIGN_RULES
    + WITHHOLDING_RULES
    + REFUNDABLE_RULES
    + PROVINCIAL_RULES
)

POSTCALC_DIAGNOSTIC_RULES = (
    POSTCALC_REFUNDABLE_RULES
    + POSTCALC_PROVINCIAL_RULES
    + POSTCALC_CARRYFORWARD_RULES
)
